### PR TITLE
added grasp offset for suction

### PR DESCRIPTION
**Pull request by PetervDooren**
needed for https://github.com/tue-robotics/tue_robocup/pull/1055

### CODE REVIEW

**Review by MatthijsBurgh — APPROVED** [review]
Very ugly this is needed

**Comment by PetervDooren** [comment]
I don't think its ugly. We need to describe the position of the grippoint of the suction cup somewhere and better here than in the code.

**Comment by MatthijsBurgh** [comment]
> I don't think its ugly. We need to describe the position of the grippoint of the suction cup somewhere and better here than in the code.

It has its own frame, that is where it is defined

**Comment by PetervDooren** [comment]
> > I don't think its ugly. We need to describe the position of the grippoint of the suction cup somewhere and better here than in the code.
> 
> It has its own frame, that is where it is defined

Then you assume the grippoint is in the same location as the gripper, which may not always be the case.

**Comment by MatthijsBurgh** [comment]
No,  but the grasp offset should be defined relative to that frame.

**Comment by PetervDooren** [comment]
I see your point, unfortunatly the current action interface only allows us to move one end-effector frame. So while this is ugly I think it is the best we can do for now

**Pull request merged**
